api_branch : origin/master
api_parser : ~
api_cfgmod : clone
api_runner : ~
api_paths  : lib
env_make : ~
env_prep : get-composer
env_post : ci-coveralls,ci-codacy
php_conf : timezone
php_exts : igbinary,memcached,yaml
app_prep : dep-composer,db-create,db-load
app_post : db-unload
app_path : bin/teavee-html-component-generator