api_branch : origin/master
api_parser : ~
api_cfgmod : clone
api_runner : ~
api_paths  : lib
php_r_cfgs : timezone
php_r_exts : igbinary,memcached,yaml
env_r_deps : ~
env_ci_ops : coveralls,codacy
app_up_ops : db-create,db-load
app_dn_ops : db-unload
app_binary : bin/teavee-html-component-generator