---

language: php

php:
  - 5.6
  - 7.0

sudo : false
git  : { depth: 3 }
env  : { global: [ { scribe_packaged: .scribe-package.yml } ] }

services : [ memcached, mysql ]
addons   : { apt: { packages: [ libyaml-dev ] } }

before_script:
  - git clone https://github.com/scr-be/build-knowledge-shared.git config

install:
  - bash config/builders/build-reqs/build-reqs.bash up-php
  - composer install -n || composer update -n
  - bash config/builders/build-reqs/build-reqs.bash up-app

script:
  - bin/phpunit --verbose --configuration phpunit.xml.dist

after_script:
  - bash config/builders/build-reqs/build-reqs.bash dn-app
  - bash config/builders/build-reqs/build-reqs.bash dn-php

...
