---

language: php

php:
  - 5.6
  - 7.0

sudo : false

git:
  depth: 3

env:
  global:
    - scribe_packaged: .scribe-package.yml

addons:
  apt:
    packages:
      - libmemcached-dev
      - libyaml-dev
      - realpath

services:
  - memcached
  - mysql

before_install:
  - which -a readlink || echo "NOT FOUND"
  - readlink --verbose -m dir/does/not/exist || echo "NOT FOUND"
  - readlink -f build/log || echo "NOT FOUND"
  - readlink --version || echo "NOT FOUND"
  - realpath --version || echo "NOT FOUND"
  - realpath --help || echo "NOT HELP"
  - readlink --help
  - git clone https://github.com/scr-be/build-knowledge-shared.git config

install:
  - bash config/builders/build-reqs/build-reqs.bash up-php
  - composer install -n || composer update -n
  - bash config/builders/build-reqs/build-reqs.bash up-app

script:
  - bin/phpunit --verbose --configuration phpunit.xml.dist

after_script:
  - bash config/builders/build-reqs/build-reqs.bash dn-app
  - bash config/builders/build-reqs/build-reqs.bash dn-php

...
