---

language: php

php:
  - 5.6
  - 7.0

sudo : false

git:
  depth: 3

env:
  global:
    - scribe_packaged: .scribe-package.yml

addons:
  apt:
    packages:
      - libmemcached-dev
      - libyaml-dev
      - coreutils
      - realpath

services:
  - memcached
  - mysql

before_install:
  - which -a realpath || echo "IDK"
  - /usr/bin/realpath --version || echo "IDK"
  - ls -lah /usr/bin || echo "IDK"
  - git clone https://github.com/scr-be/build-knowledge-shared.git config

install:
  - bash config/builders/build-reqs/build-reqs.bash up-php
  - composer install -n || composer update -n
  - bash config/builders/build-reqs/build-reqs.bash up-app

script:
  - bin/phpunit --verbose --configuration phpunit.xml.dist

after_script:
  - bash config/builders/build-reqs/build-reqs.bash dn-app
  - bash config/builders/build-reqs/build-reqs.bash dn-php

...
