---

Scribe\Teavee\HtmlGeneratorBundle\Doctrine\Entity\IconTemplate :

    type                 : entity
    options              :
        row_format       : DYNAMIC
        charset          : utf8mb4
        collate          : utf8mb4_unicode_ci
    changeTrackingPolicy : DEFERRED_EXPLICIT
    readOnly             : true
    table                : Teavee_Icon_Template
    repositoryClass      : Scribe\Teavee\HtmlGeneratorBundle\Doctrine\Repository\IconTemplateRepository

    id:

        slug :
            id     : true
            type   : string
            length : 64
            generator :
                strategy : NONE

    uniqueConstraints :

        uniqueIconSlugAndFamily :
            columns: [ slug, family ]

    fields :

        description :
            type    : string
            length  : 256

        template :
            type : text

        priority :
            type     : smallint
            nullable : true

    manyToOne :

        family :
            targetEntity : IconFamily
            inversedBy   : templates
            joinColumn   :
                name                 : family
                referencedColumnName : slug

...
